spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/company_db
    username: aliyara29
    password: Yara2001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8090/realms/InovSmart"
      client:
        registration:
          keycloak:
            client-id: "company-client"
            client-secret: "KNHK3oDDAs6C8seb9hNSRU2QuSf9eqs6"
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: "http://localhost:8090/realms/InovSmart/protocol/openid-connect/token"

keycloak:
  admin-url: "http://localhost:8090"
  realm: "InovSmart"