spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: "http://localhost:8090/realms/InovSmart"
        client:
          registration:
            keycloak:
              client-id: "company-service"
              client-secret: "Dtr70ZJR4H9h09HizMTPmg168mJ7EJ9U"
              authorization-grant-type: client_credentials
          provider:
            keycloak:
              token-uri: "http://localhost:8090/realms/InovSmart/protocol/openid-connect/token"

  keycloak:
    admin-url: "http://localhost:8090"
    realm: "InovSmart"